# Generated by Django 2.2 on 2020-04-08 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
