# Generated by Django 2.2 on 2020-04-08 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_plus_login', '0002_auto_20200408_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
