# Generated by Django 2.2 on 2020-04-08 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200408_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 9, 2, 50, 857160, tzinfo=utc)),
        ),
    ]
