# Generated by Django 2.2 on 2020-04-10 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20200410_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_detail',
            name='user_reaction',
        ),
        migrations.AddField(
            model_name='blog_detail',
            name='dislike_user_reaction',
            field=models.ManyToManyField(blank=True, related_name='dislike_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog_detail',
            name='like_user_reaction',
            field=models.ManyToManyField(blank=True, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog_detail',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 8, 16, 6, 786325, tzinfo=utc)),
        ),
    ]
