# Generated by Django 2.2 on 2020-04-12 11:09

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20200410_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 11, 9, 32, 396188, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 4, 12, 11, 9, 32, 399179, tzinfo=utc))),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete='CASCADE', related_name='commments', to='blog.Blog_Detail')),
                ('dislike_user_reaction', models.ManyToManyField(blank=True, related_name='dislike_comment_user', to=settings.AUTH_USER_MODEL)),
                ('like_user_reaction', models.ManyToManyField(blank=True, related_name='like_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
