# Generated by Django 2.2 on 2020-04-12 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200412_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 12, 4, 22, 515906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blog_Detail'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 4, 22, 517901, tzinfo=utc)),
        ),
    ]
